# Generated by Django 5.0.4 on 2024-05-05 00:30

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(verbose_name='Data')),
                ('create_at', models.DateField(blank=True, default=datetime.datetime.now)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_reservation', to='myapp.item')),
            ],
            options={
                'verbose_name': 'Registrar Reserva',
                'verbose_name_plural': 'Registrar Reservas',
                'ordering': ['-id'],
            },
        ),
    ]
